name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Clean install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps
          
      - name: Run tests
        run: npm test
        
      - name: Build
        run: npm run build

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            # Navigate to deployment directory
            cd ${{ secrets.DROPLET_PATH }}
            
            # Pull latest code
            git pull origin main
            
            # Stop and remove the old container if it exists
            docker stop ${{ github.event.repository.name }} || true
            docker rm ${{ github.event.repository.name }} || true
            
            # Build and run the new container
            docker build -t ${{ github.event.repository.name }} .
            docker run -d \
              --name ${{ github.event.repository.name }} \
              -p 80:80 \
              --restart unless-stopped \
              ${{ github.event.repository.name }} 